In [124]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Libraries

In [163]:
#Importing all the librairies we'll need
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.metrics import explained_variance_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error,r2_score
from xgboost import XGBRegressor

from sklearn.model_selection import GridSearchCV

In [164]:
train=pd.read_csv("/content/drive/MyDrive/ZINDI/IEEE Hackathon/Train_IEEE.csv")

In [165]:
test=pd.read_csv("/content/drive/MyDrive/ZINDI/IEEE Hackathon/Test_IEEE.csv")

In [166]:
train.dtypes

id                          object
asset_id                     int64
open                       float64
high                       float64
low                        float64
volume                     float64
market_cap                 float64
url_shares                 float64
unique_url_shares          float64
reddit_posts               float64
reddit_posts_score         float64
reddit_comments            float64
reddit_comments_score      float64
tweets                     float64
tweet_spam                 float64
tweet_followers            float64
tweet_quotes               float64
tweet_retweets             float64
tweet_replies              float64
tweet_favorites            float64
tweet_sentiment1           float64
tweet_sentiment2           float64
tweet_sentiment3           float64
tweet_sentiment4           float64
tweet_sentiment5           float64
tweet_sentiment_impact1    float64
tweet_sentiment_impact2    float64
tweet_sentiment_impact3    float64
tweet_sentiment_impa

In [167]:
corrs = train.corr()

In [168]:
corrs = corrs.sort_values('close', ascending = False)

# Ten most positive correlations
pd.DataFrame(corrs['close'].head(20))

close
close                    1.000000
market_cap               0.999978
high                     0.999971
low                      0.999956
open                     0.999936
market_cap_global        0.998884
volume_24h_rank          0.787742
tweet_spam               0.751862
reddit_comments          0.712700
tweet_sentiment2         0.700992
reddit_posts             0.658126
social_volume            0.614383
tweet_followers          0.597276
tweets                   0.596872
social_score             0.574412
tweet_sentiment4         0.568735
tweet_sentiment_impact5  0.565974
url_shares               0.563648
tweet_sentiment1         0.532631
unique_url_shares        0.526003

In [169]:
# fill missing values
train = train.fillna(0)
test = test.fillna(0)

In [170]:
train

id  asset_id  ...  market_cap_global         close
0      ID_322qz6         1  ...       2.818066e+11   9428.279323
1      ID_3239o9         1  ...       2.126897e+11   7967.567267
2      ID_323J9k         1  ...       1.530712e+12  49120.738484
3      ID_323y5P         1  ...       0.000000e+00      0.000000
4      ID_324kJH         1  ...       3.386925e+11  10384.798216
...          ...       ...  ...                ...           ...
12627  ID_zybd4H         1  ...       0.000000e+00      0.000000
12628  ID_zydeys         1  ...       1.978198e+11   7303.640282
12629  ID_zyfj4W         1  ...       2.493421e+11   8828.440234
12630  ID_zz5eGB         1  ...       2.757547e+11   9658.204385
12631  ID_zzwUuL         1  ...       3.836728e+11  11795.042557

[12632 rows x 49 columns]

In [171]:
test

id  asset_id  ...  percent_change_24h  market_cap_global
0     ID_323Sn2         1  ...            0.000000       0.000000e+00
1     ID_325SNW         1  ...           -0.555698       3.631052e+11
2     ID_325uzE         1  ...            1.689370       1.771075e+11
3     ID_328qCx         1  ...            0.000000       0.000000e+00
4     ID_3293uJ         1  ...            0.000000       0.000000e+00
...         ...       ...  ...                 ...                ...
6217  ID_zufSPk         1  ...           -0.967973       2.262125e+11
6218  ID_zuz9yf         1  ...            0.000000       3.523272e+11
6219  ID_zvrMSX         1  ...            0.000000       0.000000e+00
6220  ID_zy9Cfv         1  ...            0.000000       0.000000e+00
6221  ID_zyAFd7         1  ...           -3.289226       1.926557e+11

[6222 rows x 48 columns]

check duplicate

In [172]:
# Check for duplicates
train.duplicated().any(), test.duplicated().any()

(False, False)

In [173]:
# Select main columns to be used in training
features=['open','high','low','social_score','average_sentiment','volume','news','price_score','social_impact_score','correlation_rank','galaxy_score','volatility','market_cap_rank','percent_change_24h_rank','social_volume','market_cap','percent_change_24h','market_cap_global']
X = train[features]
y = train.close.astype(float)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.1, random_state=1994)

# machine learning

In [174]:
X

open          high  ...  percent_change_24h  market_cap_global
0       9422.849081   9428.490628  ...            1.434516       2.818066e+11
1       7985.359278   7992.059917  ...           -2.459507       2.126897e+11
2      49202.033778  49394.593518  ...            4.942448       1.530712e+12
3          0.000000      0.000000  ...            0.000000       0.000000e+00
4      10535.737119  10535.737119  ...            2.609576       3.386925e+11
...             ...           ...  ...                 ...                ...
12627      0.000000      0.000000  ...            0.000000       0.000000e+00
12628   7294.506136   7306.701928  ...            0.000000       1.978198e+11
12629   8811.121632   8832.560173  ...            0.000000       2.493421e+11
12630   9661.514681   9662.196605  ...            2.706432       2.757547e+11
12631  11846.368563  11846.368563  ...           -1.575454       3.836728e+11

[12632 rows x 18 columns]

In [175]:
from sklearn.ensemble import StackingRegressor

In [176]:
ss =pd.read_csv("/content/drive/MyDrive/ZINDI/IEEE Hackathon/SampleSubmission (2).csv")

In [177]:
nfolds = 10
kfolds=KFold(n_splits=nfolds, shuffle=True, random_state=1994)

In [178]:
models = [('xgb',XGBRegressor(learning_rate=0.01,n_estimators=20000,
                                     max_depth=3, min_child_weight=0,
                                     gamma=0, subsample=0.7,
                                     colsample_bytree=0.7,
                                     objective='reg:linear', nthread=-1,
                                     scale_pos_weight=1, seed=27,
                                     reg_alpha=0.006)),
          ('linearregression',LinearRegression())]

In [ ]:
y_pred_tot=[]
for ind,(ind_train,ind_val) in (enumerate (kfolds.split(X,y))): 
    X_train,X_val = X.iloc[ind_train],X.iloc[ind_val] 
    y_train,y_val = y.iloc[ind_train],y.iloc[ind_val]
    model = StackingRegressor(estimators=models)
    model.fit(X_train,y_train)
    val_pred = model.predict(X_val)
    score_val=np.sqrt(mean_squared_error(y_val, val_pred))
    print(score_val)
    test_pred = model.predict(test[features])
    y_pred_tot.append(test_pred)
    

In [149]:
len(y_pred_tot)

10

In [150]:
y_pred_tot

[array([3.67498374e-01, 1.13508389e+04, 6.31039975e+03, ...,
        4.29263422e-01, 3.66382138e-01, 7.06237159e+03]),
 array([-1.34169311e+00,  1.13513677e+04,  6.30601609e+03, ...,
        -1.34141040e+00, -1.34169822e+00,  7.06715736e+03]),
 array([-2.52311854e-01,  1.13519763e+04,  6.30528140e+03, ...,
        -2.51724840e-01, -2.52320617e-01,  7.06741246e+03]),
 array([1.00350990e+00, 1.13514636e+04, 6.30403556e+03, ...,
        1.02902383e+00, 1.00304881e+00, 7.06325878e+03]),
 array([1.96933672e+00, 1.13513779e+04, 6.31871705e+03, ...,
        1.95523703e+00, 1.96959153e+00, 7.06954231e+03]),
 array([-1.79136883e+00,  1.13489433e+04,  6.31063018e+03, ...,
        -1.78676787e+00, -1.79145198e+00,  7.07172292e+03]),
 array([1.45160050e+00, 1.13485425e+04, 6.30254800e+03, ...,
        1.46914317e+00, 1.45128346e+00, 7.06245564e+03]),
 array([3.22999668e+00, 1.13508461e+04, 6.30763113e+03, ...,
        3.26567856e+00, 3.22935183e+00, 7.06443557e+03]),
 array([-7.58958364e-01,  1.13

In [156]:
predictions=np.mean(y_pred_tot,0)
sub_file = ss.copy()
sub_file.close = predictions
sub_file.to_csv('submit.csv', index = False)